### ISSUE TITLE
b and y ions selected by default 

### ISSUE THREAD

**Issue by ypriverol** [UWPR/Lorikeet#10]
@vagisha I want to show by default b 2+ and y 2+ but I don't know by parameters if that is possible. 

<img width="162" alt="Screen Shot 2019-11-04 at 20 56 46" src="https://user-images.githubusercontent.com/52113/68157641-f7fead80-ff45-11e9-8db5-1cecb840cb2f.png">

**Comment by edeutsch** [comment]
I think it is just:
	    $("#lorikeet").specview({"sequence":"AFTEGAVLSFHNICYR",
				      "scanNum":32007,
				      "charge":3,
				      "showA":[1,1,0],
				      "showB":[1,1,0],
				      "showC":[0,0,0],
				      "showX":[0,0,0],
				      "showY":[1,1,0],
				      "showZ":[0,0,0],
...

**Comment by ypriverol** [comment]
👍
